#!/bin/sh
# SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
set -e
if [ "$1" = remove ] && [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
    deb-systemd-invoke stop farside-console-host.service farside-virtual-host.service >/dev/null || true
fi
exit 0
